name: summary-bot

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  models: read
  issues: write

jobs:
  run-summary-bot:
    if: contains(github.event.comment.body, '@summary-bot')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      DEFAULT_INSTRUCTION: 以下のGitHub Issueの議論を要約して。
      # you can choose a model from https://github.com/marketplace?type=models
      MODEL_NAME: gpt-4.1-mini
    steps:
      - uses: actions/checkout@v4
      - name: Setup gh extension
        run: gh extension install https://github.com/github/gh-models
      - name: Get model response and comment
        run: |
          EVENT_PATH=$GITHUB_EVENT_PATH
          COMMENT_BODY=$(jq -r .comment.body "$EVENT_PATH")
          INSTRUCTION=$(echo "$COMMENT_BODY" | sed -n 's/.*@summary-bot\s*\(.*\)/\1/p')

          if [ -z "$INSTRUCTION" ]; then
            INSTRUCTION="${{ env.DEFAULT_INSTRUCTION }}"
          fi

          CONTENT="$(gh issue view 2 --comments --json title,author,body,comments --template '
          Issue title: {{.title}}
          Issue author: {{.author.login}}
          Issue body: {{.body}}
          ==={{range .comments}}
          Comment author: {{.author.login}}
          Comment body: {{.body}}
          ==={{end}}
          ')"
          echo "CONTENT:"
          echo "$CONTENT"

          # 3. LLMへの入力を構成
          INPUT="$INSTRUCTION\n---\n$CONTENT"
          echo "INPUT:"
          echo "$INPUT"

          RESPONSE="$(gh models run ${{ env.MODEL_NAME }} \"$INPUT\")"
          echo "RESPONSE:"
          echo "$RESPONSE"

          gh issue comment ${{ github.event.issue.number }} --body "$RESPONSE"
