name: summary-bot

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  models: read
  issues: write

jobs:
  run-summary-bot:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      DEFAULT_INSTRUCTION: 以下のGitHub Issueの議論を要約して。
    steps:
      - uses: actions/checkout@v4
      - name: Setup gh extension
        run: gh extension install https://github.com/github/gh-models
      - name: Get model response
        run: |
          EVENT_PATH=$GITHUB_EVENT_PATH
          COMMENT_BODY=$(jq -r .comment.body "$EVENT_PATH")
          COMMENT_USER=$(jq -r .comment.user.login "$EVENT_PATH")
          ISSUE_URL=$(jq -r .issue.url "$EVENT_PATH")
          ISSUE_COMMENTS_URL=$(jq -r .issue.comments_url "$EVENT_PATH")
          ISSUE_TITLE=$(jq -r .issue.title "$EVENT_PATH")
          ISSUE_BODY=$(jq -r .issue.body "$EVENT_PATH")
          INSTRUCTION=$(echo "$COMMENT_BODY" | sed -n 's/.*@summary-bot\s*\(.*\)/\1/p')

          if [ -z "$INSTRUCTION" ]; then
            INSTRUCTION="${{ env.DEFAULT_INSTRUCTION }}"
          fi

          COMMENTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$ISSUE_COMMENTS_URL" | jq -r '.[] | "\(.user.login): \(.body)"' | tr '\n' '\\n')
          echo "$COMMENTS"

          # 3. LLMへの入力を構成
          INPUT="$INSTRUCTION\n---\nIssue Title: $ISSUE_TITLE\n\nIssue Body:\n$ISSUE_BODY\n\nComments:\n$COMMENTS"
          echo "$INPUT"

          RESPONSE="$(gh models run gpt-4.1-mini \"$INPUT\")"
          echo "$RESPONSE"

          gh issue comment ${{ github.event.issue.number }} --body "$RESPONSE"
